# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        stages: [commit, merge-commit]
    -   id: end-of-file-fixer
        stages: [commit, merge-commit]
    -   id: check-yaml
        stages: [commit, merge-commit]
    -   id: check-added-large-files
        stages: [commit, merge-commit]
    -   id: check-ast
        stages: [commit, merge-commit]
    -   id: check-case-conflict
        stages: [commit, merge-commit]
    -   id: requirements-txt-fixer
        stages: [commit, merge-commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        stages: [commit, merge-commit]
