# Generated by Django 3.1.1 on 2020-09-26 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='rec_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date recorded'),
            preserve_default=False,
        ),
    ]
