# Generated by Django 3.1.1 on 2020-09-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_voice', '0002_recording_rec_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
